-- DELIMITADOR PERSONALIZADO
DELIMITER //

-- CREAR PROCEDIMIENTO
CREATE PROCEDURE VerRegistros (IN Condicion VARCHAR(30))

BEGIN
    SELECT *
    FROM Clientes
    WHERE ID LIKE CONCAT (Condicion, '%')
    OR Nombre LIKE CONCAT (Condicion, '%');
END // 

-- RESTAURAR EL DELIMITADOR
DELIMITER //

-- EJECUTAR EL PROCEDIMIENTO
CALL VerRegistros('Mari');
